# Generated by Django 4.2.6 on 2023-11-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
